baseURL = "https://blog.pedsgimind.ca/"
languageCode = "en"
title = "PedsGIMind | Multilingual Digestive Health & Medical Education"
theme = "PaperMod"

canonifyURLs = true
relativeURLs = false
defaultContentLanguage = "en"
enableRobotsTXT = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1

  [languages.fr]
    languageName = "Français"
    languageCode = "fr"
    weight = 2

  [languages.es]
    languageName = "Español"
    languageCode = "es"
    weight = 3

  [languages.ar]
    languageName = "العربية"
    languageCode = "ar"
    weight = 4
    rtl = true

  [languages.ku]
    languageName = "Kurdî"
    languageCode = "ku"
    weight = 5
    rtl = true

  [languages.fa]
    languageName = "فارسی"
    languageCode = "fa"
    weight = 6
    rtl = true

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
